# Generated by Django 5.2.1 on 2025-05-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='collaborations/')),
                ('category', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
